apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nxrm-aws-resiliency.fullname" . }}
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
    {{- include "nxrm-aws-resiliency.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  storageClassName: local-storage
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
